#lang racket/base
(require "helpers.rkt")
(provide MakeConsole)



(define (MakeConsole)
  (let ((_scope 0))
    (define (dispatch msg . args)
      (apply
        (case msg
          ((position)  position)
          ((velocity)  velocity)
          ((ellipse)   shape_ellipse)
          ((rectangle) shape_rectangle)
          ((score)     score)
          ((warning)   warning)
          (else
            (method_missing msg dispatch)))
        args))

    (define (position pos)
      (let ((x (pos 'x))
            (y (pos 'y)))
        (scope)
        (display "Position:")
        (indent!)
        (scope)
        (display "_x = ")
        (display x)
        (scope)
        (display "_y = ")
        (display y)
        (dedent!)))

    (define (velocity vel)
      (let ((horizontal (vel 'horizontal))
            (vertical   (vel 'vertical)))
        (scope)
        (display "Velocity:")
        (indent!)
        (scope)
        (display "_h = ")
        (display horizontal)
        (scope)
        (display "_v = ")
        (display vertical)
        (dedent!)))

    (define (shape_ellipse ellipse color)
      (scope)
      (display "ShapeEllipse: <")
      (display color)
      (display ">")
      (shape ellipse))

    (define (shape_rectangle rectangle color)
      (scope)
      (display "ShapeRectangle: <")
      (display color)
      (display ">")
      (shape rectangle))

    (define (shape shape)
      (let ((pos    (shape 'position))
            (vel    (shape 'velocity))
            (width  (shape 'width))
            (height (shape 'height)))
        (indent!)
        (scope)
        (display "_w = ")
        (display width)
        (scope)
        (display "_h = ")
        (display height)
        (position pos)
        (velocity vel)
        (dedent!)))

    (define (score score)
      (let ((curr (score 'current))
            (high (score 'highest)))
        (scope)
        (display "Score:")
        (indent!)
        (scope)
        (display "_c: ")
        (display curr)
        (scope)
        (display "_h: ")
        (display high)
        (dedent!)))

    (define (warning str)
      (scope)
      (display "WARNING: ")
      (display str))

    (define (scope)
      (newline)
      (let iter ((ctr _scope))
        (unless (= ctr 0)
          (display " . ")
          (iter (- ctr 1)))))

    (define (indent!) (set! _scope (+ _scope 1)))
    (define (dedent!) (set! _scope (- _scope 1)))

    dispatch))
